[build-system]
requires = ['setuptools', 'wheel', 'setuptools-scm']
build-backend = 'setuptools.build_meta'

[project]
name='pagerlib'
authors = [{name='38dunn', email='38dunn@gmail.com'}]

readme = 'README.md'
license = {file = 'LICENSE'}

requires-python = '>=3.9'

dependencies = [
  'pytesseract',
  'pdf2image',
  'numpy',
  'opencv-python',
  'matplotlib',
  'python-docx',
  'scipy',
  'scikit-learn',
  'transformers',
  'torch',
  'torchvision',
  'torch-geometric',
  'python-multipart',
  'pdfminer.six==20251107'
]

version = '0.0.10' 

[tool.setuptools.packages.find]
where = ["src"]